# Generated by Django 5.1 on 2024-08-23 02:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ciudad',
            fields=[
                ('idCiudad', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='EstadoVisita',
            fields=[
                ('idEV', models.AutoField(primary_key=True, serialize=False)),
                ('nomEstado', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='TipoReciclaje',
            fields=[
                ('idTR', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='TipoUsuario',
            fields=[
                ('idTR', models.AutoField(primary_key=True, serialize=False)),
                ('desc', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('email', models.EmailField(max_length=70, primary_key=True, serialize=False, unique=True)),
                ('username', models.CharField(max_length=50)),
                ('nombre', models.CharField(max_length=50)),
                ('apellido', models.CharField(max_length=50)),
                ('fechaNac', models.DateField()),
                ('estado', models.BooleanField(default=True)),
                ('telefono', models.CharField(max_length=50)),
                ('foto', models.CharField(max_length=50)),
                ('fechaReg', models.DateField(auto_now_add=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
                ('tipoUser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.tipousuario')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Comuna',
            fields=[
                ('idComuna', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('idCiudad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.ciudad')),
            ],
        ),
        migrations.CreateModel(
            name='Direcciones',
            fields=[
                ('idDireccion', models.AutoField(primary_key=True, serialize=False)),
                ('calle', models.CharField(max_length=50)),
                ('nro', models.IntegerField()),
                ('emailUser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('nomComuna', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.comuna')),
            ],
        ),
        migrations.CreateModel(
            name='Publicacion',
            fields=[
                ('idPublicacion', models.AutoField(primary_key=True, serialize=False)),
                ('desc', models.CharField(max_length=256)),
                ('img', models.CharField(max_length=50)),
                ('emailUsuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PuntoVerde',
            fields=[
                ('idPv', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('direccion', models.CharField(max_length=50)),
                ('nro', models.IntegerField()),
                ('estado', models.BooleanField(default=False)),
                ('nomComuna', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.comuna')),
            ],
        ),
        migrations.CreateModel(
            name='RegistroRetiro',
            fields=[
                ('idRetiro', models.AutoField(primary_key=True, serialize=False)),
                ('fechaReg', models.DateField(auto_now_add=True)),
                ('fechaVisita', models.DateField()),
                ('horaVisita', models.DateField()),
                ('desc', models.CharField(max_length=256)),
                ('emailUser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('estadoVisita', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.estadovisita')),
                ('idDireccion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.direcciones')),
            ],
        ),
        migrations.CreateModel(
            name='SugRec',
            fields=[
                ('idSR', models.AutoField(primary_key=True, serialize=False)),
                ('asunto', models.CharField(max_length=50)),
                ('desc', models.CharField(max_length=256)),
                ('emailUsuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TipoReciclajePv',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idPv', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.puntoverde')),
                ('idTr', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.tiporeciclaje')),
            ],
        ),
    ]
