# Generated by Django 5.1 on 2024-11-12 15:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ciudad',
            fields=[
                ('idCiudad', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='EstadoVisita',
            fields=[
                ('idEV', models.AutoField(primary_key=True, serialize=False)),
                ('nomEstado', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Metas',
            fields=[
                ('idMeta', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=150)),
                ('desc', models.CharField(max_length=500)),
                ('finalMeta', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('idProducto', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('desc', models.CharField(max_length=256)),
                ('precio', models.IntegerField()),
                ('stock', models.IntegerField()),
                ('imagen', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='SugRec',
            fields=[
                ('idSR', models.AutoField(primary_key=True, serialize=False)),
                ('asunto', models.CharField(max_length=50)),
                ('desc', models.CharField(max_length=256)),
                ('emailUsuario', models.CharField(max_length=70)),
            ],
        ),
        migrations.CreateModel(
            name='TipoReciclaje',
            fields=[
                ('idTR', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('imagen', models.CharField(max_length=100, null=True)),
                ('desc', models.CharField(max_length=1000, null=True)),
                ('comollevar', models.CharField(max_length=1000, null=True)),
                ('reconocer', models.CharField(max_length=1000, null=True)),
                ('nollevar', models.CharField(max_length=1000, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TipoUsuario',
            fields=[
                ('idTR', models.AutoField(primary_key=True, serialize=False)),
                ('desc', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('email', models.EmailField(max_length=70, primary_key=True, serialize=False, unique=True)),
                ('username', models.CharField(max_length=50)),
                ('nombre', models.CharField(max_length=50, null=True)),
                ('apellido', models.CharField(max_length=50, null=True)),
                ('fechaNac', models.DateField(null=True)),
                ('estado', models.BooleanField(default=True)),
                ('telefono', models.CharField(max_length=50, null=True)),
                ('foto', models.CharField(max_length=50, null=True)),
                ('fechaReg', models.DateField(auto_now_add=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
                ('tipoUser', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.tipousuario')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Comuna',
            fields=[
                ('idComuna', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('idCiudad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.ciudad')),
            ],
        ),
        migrations.CreateModel(
            name='Direcciones',
            fields=[
                ('idDireccion', models.AutoField(primary_key=True, serialize=False)),
                ('calle', models.CharField(max_length=50)),
                ('nro', models.IntegerField()),
                ('emailUser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('nomComuna', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.comuna')),
            ],
        ),
        migrations.CreateModel(
            name='Publicacion',
            fields=[
                ('idPublicacion', models.AutoField(primary_key=True, serialize=False)),
                ('desc', models.CharField(max_length=256)),
                ('img', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('timeCreate', models.DateTimeField(auto_now_add=True)),
                ('likes_count', models.IntegerField(default=0)),
                ('estado', models.BooleanField(default=False)),
                ('emailUsuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Comentario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contenido', models.TextField()),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('publicacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comentarios', to='api.publicacion')),
            ],
        ),
        migrations.CreateModel(
            name='PuntoVerde',
            fields=[
                ('idPv', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('direccion', models.CharField(max_length=50)),
                ('nro', models.IntegerField()),
                ('estado', models.BooleanField(default=False)),
                ('nomComuna', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.comuna')),
            ],
        ),
        migrations.CreateModel(
            name='PuntuacioUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('puntosplas', models.IntegerField()),
                ('puntospapel', models.IntegerField()),
                ('putnosvidrio', models.IntegerField()),
                ('puntoscarton', models.IntegerField()),
                ('puntoslatas', models.IntegerField()),
                ('emailusuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='RegistroRetiro',
            fields=[
                ('idRetiro', models.AutoField(primary_key=True, serialize=False)),
                ('fechaReg', models.DateField(auto_now_add=True)),
                ('fechaVisita', models.DateField()),
                ('horaVisita', models.DateField()),
                ('desc', models.CharField(max_length=256)),
                ('emailUser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('estadoVisita', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.estadovisita')),
                ('idDireccion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.direcciones')),
            ],
        ),
        migrations.CreateModel(
            name='TipoReciclajePv',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idPv', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.puntoverde')),
                ('idTr', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.tiporeciclaje')),
            ],
        ),
        migrations.CreateModel(
            name='TransPuntos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('puntosplas', models.IntegerField()),
                ('puntospapel', models.IntegerField()),
                ('putnosvidrio', models.IntegerField()),
                ('puntoscarton', models.IntegerField()),
                ('puntoslatas', models.IntegerField()),
                ('fechatrans', models.DateField(auto_now_add=True)),
                ('estado', models.BooleanField(default=True)),
                ('emailusuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ProgresoUsuarioMeta',
            fields=[
                ('idPUM', models.AutoField(primary_key=True, serialize=False)),
                ('progreso', models.IntegerField()),
                ('completado25', models.BooleanField(default=False)),
                ('completado50', models.BooleanField(default=False)),
                ('completado75', models.BooleanField(default=False)),
                ('completado100', models.BooleanField(default=False)),
                ('emailUser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('idMeta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.metas')),
            ],
            options={
                'unique_together': {('emailUser', 'idMeta')},
            },
        ),
        migrations.CreateModel(
            name='Like',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to=settings.AUTH_USER_MODEL)),
                ('publicacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='api.publicacion')),
            ],
            options={
                'unique_together': {('usuario', 'publicacion')},
            },
        ),
    ]
