# Generated by Django 5.1 on 2024-10-27 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_usuario_apellido_alter_usuario_fechanac_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tiporeciclajepv',
            name='imagen',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
