# Generated by Django 5.1 on 2024-11-25 22:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_puntoverde_lat_puntoverde_lng_usuario_is_staff_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='puntoverde',
            name='lat',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='puntoverde',
            name='lng',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='PesoUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pesoplas', models.IntegerField()),
                ('pesopal', models.IntegerField()),
                ('pesovid', models.IntegerField()),
                ('pesocar', models.IntegerField()),
                ('pesolat', models.IntegerField()),
                ('emailusuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
