# Generated by Django 5.1 on 2024-10-27 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_tiporeciclajepv_imagen'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tiporeciclajepv',
            name='imagen',
        ),
        migrations.AddField(
            model_name='tiporeciclaje',
            name='imagen',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
