# Generated by Django 5.1 on 2024-11-25 22:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_puntoverde_lat_puntoverde_lng_pesousuario'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='puntoverde',
            name='lat',
        ),
        migrations.RemoveField(
            model_name='puntoverde',
            name='lng',
        ),
    ]
