# Generated by Django 5.1 on 2024-11-25 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_remove_puntoverde_lat_remove_puntoverde_lng'),
    ]

    operations = [
        migrations.AddField(
            model_name='puntoverde',
            name='lat',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='puntoverde',
            name='lng',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
