# Generated by Django 5.1 on 2024-10-27 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_remove_tiporeciclajepv_imagen_tiporeciclaje_imagen'),
    ]

    operations = [
        migrations.AddField(
            model_name='tiporeciclaje',
            name='desc',
            field=models.CharField(max_length=1000, null=True),
        ),
    ]
