# Generated by Django 5.1 on 2024-10-27 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_tiporeciclaje_desc'),
    ]

    operations = [
        migrations.AddField(
            model_name='tiporeciclaje',
            name='comollevar',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='tiporeciclaje',
            name='nollevar',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='tiporeciclaje',
            name='reconocer',
            field=models.CharField(max_length=1000, null=True),
        ),
    ]
