# Generated by Django 5.1 on 2024-12-03 16:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_puntoverde_lat_puntoverde_lng'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transpuntos',
            old_name='puntoscarton',
            new_name='cantidadpeso',
        ),
        migrations.RenameField(
            model_name='transpuntos',
            old_name='puntoslatas',
            new_name='cantidadpuntos',
        ),
        migrations.RemoveField(
            model_name='transpuntos',
            name='puntospapel',
        ),
        migrations.RemoveField(
            model_name='transpuntos',
            name='puntosplas',
        ),
        migrations.RemoveField(
            model_name='transpuntos',
            name='putnosvidrio',
        ),
        migrations.AddField(
            model_name='transpuntos',
            name='tiporec',
            field=models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, to='api.tiporeciclaje'),
        ),
        migrations.CreateModel(
            name='Notificacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mensaje', models.TextField()),
                ('fecha_envio', models.DateTimeField(auto_now_add=True)),
                ('leido', models.BooleanField(default=False)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('idPedido', models.AutoField(primary_key=True, serialize=False)),
                ('puntos_utilizados', models.IntegerField()),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('direccion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.direcciones')),
                ('productos', models.ManyToManyField(to='api.producto')),
            ],
        ),
        migrations.CreateModel(
            name='TransPeso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidadpeso', models.IntegerField()),
                ('fechatrans', models.DateField(auto_now_add=True)),
                ('estado', models.BooleanField(default=True)),
                ('emailusuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('tiporec', models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, to='api.tiporeciclaje')),
            ],
        ),
    ]
