# Generated by Django 5.1 on 2024-10-29 15:36

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_tiporeciclaje_comollevar_tiporeciclaje_nollevar_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='publicacion',
            name='likes',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='publicacion',
            name='timeCreate',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='publicacion',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='post_images/'),
        ),
    ]
