# Generated by Django 5.1 on 2024-10-27 19:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_tiporeciclaje_comollevar_tiporeciclaje_nollevar_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PuntuacioUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('puntosplas', models.IntegerField()),
                ('puntospapel', models.IntegerField()),
                ('putnosvidrio', models.IntegerField()),
                ('puntoscarton', models.IntegerField()),
                ('puntoslatas', models.IntegerField()),
                ('emailusuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TransPuntos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('puntosplas', models.IntegerField()),
                ('puntospapel', models.IntegerField()),
                ('putnosvidrio', models.IntegerField()),
                ('puntoscarton', models.IntegerField()),
                ('puntoslatas', models.IntegerField()),
                ('fechatrans', models.DateField(auto_now_add=True)),
                ('estado', models.BooleanField(default=True)),
                ('emailusuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
