# Generated by Django 5.1 on 2024-10-31 19:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_publicacion_likes_publicacion_timecreate_and_more'),
        ('api', '0007_puntuaciousuario_transpuntos'),
    ]

    operations = [
    ]
