# Generated by Django 5.1 on 2024-10-31 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_merge_20241031_1636'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publicacion',
            name='img',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
