# Generated by Django 5.1 on 2024-10-31 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_alter_publicacion_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sugrec',
            name='emailUsuario',
            field=models.CharField(max_length=70),
        ),
    ]
