# Generated by Django 5.1 on 2024-11-08 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_producto'),
    ]

    operations = [
        migrations.AddField(
            model_name='publicacion',
            name='estado',
            field=models.BooleanField(default=False),
        ),
    ]
