# Generated by Django 5.1 on 2024-11-08 03:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_producto'),
    ]

    operations = [
        migrations.RenameField(
            model_name='publicacion',
            old_name='likes',
            new_name='likes_count',
        ),
    ]
